import React, { useRef } from 'react'

import * as THREE from 'three'
import { GroupProps, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
// import { a as three } from '@react-spring/three'

const vec = new THREE.Vector3()

export default function Model({ open, ...props }): React.ReactElement {
  const group = useRef<GroupProps>()
  const { nodes, materials } = useGLTF('/images/3dObjects/iPad2020Pro.glb')

  // Make it float in the air when it's opened
  useFrame(state => {
    const t = state.clock.getElapsedTime()
    state.camera.position.lerp(vec.set(0, 0, 20), 0.1)
    state.camera.lookAt(0, 0, 0)

    // rotations
    // group.current.rotation.x = THREE.MathUtils.lerp(
    //   group.current.rotation.x,
    //   open ? Math.cos(t / 2) / 8 + 2 : 1.5,
    //   0.1
    // )

    // group.current.rotation.y = THREE.MathUtils.lerp(
    //   group.current.rotation.y,
    //   Math.sin(t / 4) / 60,
    //   0.1
    // )
    // group.current.rotation.z = THREE.MathUtils.lerp(
    //   group.current.rotation.z,
    //   open ? Math.sin(t / 4) / 20 : 3,
    //   0.1
    // )

    // // positions
    // group.current.position.y = THREE.MathUtils.lerp(
    //   group.current.position.y,
    //   (-1 + Math.sin(t)) / 6,
    //   0.1
    // )
  })

  // The view was auto-generated by: https://github.com/pmndrs/gltfjsx
  // Events and spring animations were added afterwards
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.29, 156.35, -2.1]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI, 0, Math.PI]} scale={[1, 1, 1]}>
            <group
              position={[-0.01, -5.08, -0.06]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[1, 1, 1]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011.geometry}
                material={nodes.Cylinder011.material}
                position={[-0.2, 0, -0.01]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012.geometry}
                material={nodes.Cylinder012.material}
                position={[0, 0, -0.01]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013.geometry}
                material={nodes.Cylinder013.material}
                position={[0.2, 0, -0.01]}
              />
            </group>
            <group
              position={[3.73, 5.02, -0.12]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[1, 1, 1]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014.geometry}
                material={nodes.Cylinder014.material}
                position={[0, 0, 0.03]}
              />
              <group position={[0, 0, -0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder015_1.geometry}
                  material={nodes.Cylinder015_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder015_2.geometry}
                  material={nodes.Cylinder015_2.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder015_3.geometry}
                  material={nodes.Cylinder015_3.material}
                />
              </group>
            </group>
            <group
              position={[-0.01, -0.01, 0.04]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 1, 1]}
            >
              <lineSegments
                geometry={nodes.Line031.geometry}
                material={nodes.Line031.material}
                position={[4.22, 0, -4.97]}
                rotation={[0, 0, Math.PI]}
                scale={[1, 1, 1]}
              />
              <lineSegments
                geometry={nodes.Line032.geometry}
                material={nodes.Line032.material}
                position={[4.22, 0, 4.97]}
                rotation={[-Math.PI, 0, 0]}
              />
              <lineSegments
                geometry={nodes.Line033.geometry}
                material={nodes.Line033.material}
                position={[1.22, 0, 5.51]}
                rotation={[-Math.PI, Math.PI / 2, 0]}
                scale={[-1, 1, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line034.geometry}
                material={nodes.Line034.material}
                position={[-0.59, -0.11, 5.17]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[-1, 1, 1]}
              />
              <lineSegments
                geometry={nodes.Line035.geometry}
                material={nodes.Line035.material}
                position={[-4.22, 0, 4.97]}
                rotation={[0, 0, Math.PI]}
                scale={[-1, 1, 1]}
              />
              <lineSegments
                geometry={nodes.Line036.geometry}
                material={nodes.Line036.material}
                position={[-4.22, 0, -4.97]}
                rotation={[-Math.PI, 0, 0]}
                scale={[1, 1, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line037.geometry}
                material={nodes.Line037.material}
                position={[-0.59, -0.11, -5.17]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
                scale={[1, 1, 1]}
              />
              <lineSegments
                geometry={nodes.Line038.geometry}
                material={nodes.Line038.material}
                position={[-1.22, 0, -5.51]}
                rotation={[-Math.PI, Math.PI / 2, 0]}
                scale={[1, 1, 1]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Color177.geometry}
              material={nodes.Color177.material}
              position={[-0.01, -0.01, 0.15]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box010.geometry}
              material={nodes.Box010.material}
              position={[4.16, -0.02, 0.04]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box011.geometry}
              material={nodes.Box011.material}
              position={[4.16, 4.03, 0.04]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.96, 0.96, 0.96]}
            />
            <group
              position={[0.27, -0.26, 0.15]}
              rotation={[-Math.PI, 0, Math.PI]}
              scale={[1, 1, 1]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_1.geometry}
                material={nodes.Line030_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_2.geometry}
                material={nodes.Line030_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_3.geometry}
                material={nodes.Line030_3.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_4.geometry}
                material={nodes.Line030_4.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_5.geometry}
                material={nodes.Line030_5.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Line030_6.geometry}
                material={nodes.Line030_6.material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Color178.geometry}
              material={nodes.Color178.material}
              position={[-0.01, 0.11, -0.09]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[1, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box012.geometry}
              material={nodes.Box012.material}
              position={[3.49, 5.46, 0.04]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.96, 0.96, 0.96]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Box013.geometry}
              material={nodes.Box013.material}
              position={[4.16, 4.5, 0.04]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.96, 0.96, 0.96]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Text003.geometry}
              material={nodes.Text003.material}
              position={[-0.08, -3.38, -0.07]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[1, 1, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[3.02, 157.09, -0.46]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group
            position={[-0.01, -5.08, -0.06]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder016.geometry}
              material={nodes.Cylinder016.material}
              position={[-0.2, 0, -0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017.geometry}
              material={nodes.Cylinder017.material}
              position={[0, 0, -0.01]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder018.geometry}
              material={nodes.Cylinder018.material}
              position={[0.2, 0, -0.01]}
            />
          </group>
          <group
            position={[3.73, 5.02, -0.12]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder019.geometry}
              material={nodes.Cylinder019.material}
              position={[0, 0, 0.03]}
            />
            <group position={[0, 0, -0.04]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_1.geometry}
                material={nodes.Cylinder020_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_2.geometry}
                material={nodes.Cylinder020_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_3.geometry}
                material={nodes.Cylinder020_3.material}
              />
            </group>
          </group>
          <group
            position={[-0.01, -0.01, 0.04]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 1, 1]}
          >
            <lineSegments
              geometry={nodes.Line040.geometry}
              material={nodes.Line040.material}
              position={[4.22, 0, -4.97]}
              rotation={[0, 0, Math.PI]}
              scale={[1, 1, 1]}
            />
            <lineSegments
              geometry={nodes.Line041.geometry}
              material={nodes.Line041.material}
              position={[4.22, 0, 4.97]}
              rotation={[-Math.PI, 0, 0]}
            />
            <lineSegments
              geometry={nodes.Line042.geometry}
              material={nodes.Line042.material}
              position={[1.22, 0, 5.51]}
              rotation={[-Math.PI, Math.PI / 2, 0]}
              scale={[-1, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line043.geometry}
              material={nodes.Line043.material}
              position={[-0.59, -0.11, 5.17]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[-1, 1, 1]}
            />
            <lineSegments
              geometry={nodes.Line044.geometry}
              material={nodes.Line044.material}
              position={[-4.22, 0, 4.97]}
              rotation={[0, 0, Math.PI]}
              scale={[-1, 1, 1]}
            />
            <lineSegments
              geometry={nodes.Line045.geometry}
              material={nodes.Line045.material}
              position={[-4.22, 0, -4.97]}
              rotation={[-Math.PI, 0, 0]}
              scale={[1, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line046.geometry}
              material={nodes.Line046.material}
              position={[-0.59, -0.11, -5.17]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={[1, 1, 1]}
            />
            <lineSegments
              geometry={nodes.Line047.geometry}
              material={nodes.Line047.material}
              position={[-1.22, 0, -5.51]}
              rotation={[-Math.PI, Math.PI / 2, 0]}
              scale={[1, 1, 1]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Color179.geometry}
            material={nodes.Color179.material}
            position={[-0.01, -0.01, 0.15]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box014.geometry}
            material={nodes.Box014.material}
            position={[4.16, -0.02, 0.04]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box015.geometry}
            material={nodes.Box015.material}
            position={[4.16, 4.03, 0.04]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.96, 0.96, 0.96]}
          />
          <group
            position={[0.27, -0.26, 0.15]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[1, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_1.geometry}
              material={nodes.Line039_1.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_2.geometry}
              material={nodes.Line039_2.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_3.geometry}
              material={nodes.Line039_3.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_4.geometry}
              material={nodes.Line039_4.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_5.geometry}
              material={nodes.Line039_5.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Line039_6.geometry}
              material={nodes.Line039_6.material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Color180.geometry}
            material={nodes.Color180.material}
            position={[-0.01, 0.11, -0.09]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box016.geometry}
            material={nodes.Box016.material}
            position={[3.49, 5.46, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.96, 0.96, 0.96]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box017.geometry}
            material={nodes.Box017.material}
            position={[4.16, 4.5, 0.04]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.96, 0.96, 0.96]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text004.geometry}
            material={nodes.Text004.material}
            position={[-0.08, -3.38, -0.07]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1, 1, 1]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/images/3dObjects/iPad2020Pro.glb')
